version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "jamesrweb"
    labels:
      - "dependencies"
    groups:
      development-dependencies:
        dependency-type: "development"
      react:
        patterns:
          - "react*"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
