name: CD

on:
  push:
    branches: [master]

concurrency: cd-${{ github.ref }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: P5-wrapper/setup-action@v1.0.6
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Build the components
        run: pnpm build

      - uses: JS-DevTools/npm-publish@v3
        with:
          access: "public"
          token: ${{ secrets.NPM_TOKEN }}
