name: CI

on:
  pull_request:
    branches: [master]

concurrency: ci-${{ github.ref }}

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - uses: P5-wrapper/setup-action@v1.0.6
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Run format if the PR is from the Dependabot
        if: github.actor == 'dependabot[bot]'
        run: pnpm --if-present format
        shell: bash

      - name: Commit any formatting changes
        if: github.actor == 'dependabot[bot]'
        uses: stefanzweifel/git-auto-commit-action@v5.0.0
        with:
          commit_message: Apply formatting updates
          branch: ${{ github.head_ref }}
          token: ${{ secrets.GH_TOKEN }}

  format:
    runs-on: ubuntu-latest
    needs: dependabot
    steps:
      - uses: P5-wrapper/setup-action@v1.0.6
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Check formatting
        run: pnpm --if-present format:check

      - name: Formatting issues detected (attempting fix...)
        if: ${{ failure() }}
        run: pnpm --if-present format

      - name: Commit fixed formatting issues
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply fixed formatting issues
          branch: ${{ github.head_ref }}

  lint:
    runs-on: ubuntu-latest
    needs: dependabot
    steps:
      - uses: P5-wrapper/setup-action@v1.0.6
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Lint
        run: pnpm --if-present lint

      - name: Linting issues detected (attempting fix...)
        if: ${{ failure() }}
        run: pnpm --if-present lint:fix

      - name: Commit fixed linting issues
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply fixed linting issues
          branch: ${{ github.head_ref }}

  test:
    runs-on: ubuntu-latest
    needs: dependabot
    steps:
      - uses: P5-wrapper/setup-action@v1.0.6
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Test
        run: pnpm --if-present test

  build:
    runs-on: ubuntu-latest
    needs: dependabot
    steps:
      - uses: P5-wrapper/setup-action@v1.0.6
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Build
        run: pnpm build
