name: CD

on:
  push:
    branches: [master]
  workflow_dispatch:

concurrency:
  group: cd-${{ github.ref }}
  cancel-in-progress: false

permissions: {}

jobs:
  npm:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup environment
        uses: ./.github/actions/setup
        with:
          registry-url: "https://registry.npmjs.org"

      - name: Build the component
        run: pnpm build

      - name: Run tests
        run: pnpm test

      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v4
        with:
          access: "public"
          provenance: true
          token: ${{ secrets.NPM_TOKEN }}
